// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrveujmleeptryuyqdib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydmV1am1sZWVwdHJ5dXlxZGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjY5NDcsImV4cCI6MjA2NTg0Mjk0N30.qfBctvdIzr0pzpelsMFB9Ay5iOYSrCQraeQIR3AfGIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);